# Elasticsearch Configuration
cluster.name: "dmarc-cluster"
node.name: "dmarc-node"
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Network settings
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node

# Performance optimizations
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 20%
indices.memory.min_index_buffer_size: 96mb

# Index settings for DMARC data
action.auto_create_index: "+parsedmarc-*,-*"

# Thread pool optimizations
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# Disable X-Pack security for development
xpack.security.enabled: false
xpack.monitoring.collection.enabled: false

# CORS settings for frontend integration
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: "GET, POST, PUT, DELETE, OPTIONS, HEAD"
http.cors.allow-headers: "X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization"
http.cors.allow-credentials: true

# Disk usage settings
cluster.routing.allocation.disk.threshold_enabled: false
